name: trigger_status
run-name: ${{ github.head_ref || github.ref_name }}-${{ github.run_number }} 
on:
  pull_request:
    types:
      [opened, synchronize, reopened]
jobs: 
  enforce-all-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.CLEVERTAP_PLATFORM_BOT_ID }}
          private_key: ${{ secrets.CLEVERTAP_PLATFORM_BOT_PRIVATE_ACCESS_KEY }}
      - name: Get Combined Commit Status
        run: |
          echo ${{ steps.generate_token.outputs.token }}
          curl -L -H "Accept: application/vnd.github+json" -X POST -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" -H "X-GitHub-Api-Version: 2022-11-28" -d '{"state":"pending","target_url":"https://google.com","description":"The build pending","context":"continuous-integration/macha"}'  https://api.github.com/repos/Yashprime1/genzinfra-cloudformation/statuses/${{ github.sha }}
          